packages:
  - projects/*

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - angular-extended-builder
  - "@angular/*"
  - "@angular-devkit/*"
  - "@schematics/angular"
  - ng-packagr

verifyDepsBeforeRun: false

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lefthook: true
  lmdb: true
  msgpackr-extract: true
  less: false
